# Generated by Django 4.2.23 on 2025-08-05 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_subject_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0002_classroom_classroom_id'),
        ('attendance', '0002_alter_attendancerecord_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTotalSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_session_totals', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_session_totals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__first_name', 'student__last_name'],
                'unique_together': {('student', 'classroom', 'subject')},
            },
        ),
    ]
