# Generated by Django 4.2.23 on 2025-08-05 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroom_classroom_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0002_subject_subject_id'),
        ('attendance', '0003_studenttotalsessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCustomAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_custom_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_custom_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Custom Attendance',
                'verbose_name_plural': 'Student Custom Attendance Records',
                'ordering': ['student__first_name', 'student__last_name'],
                'unique_together': {('student', 'classroom', 'subject')},
            },
        ),
    ]
